### ISSUE TITLE
async import is not being awaited correctly

### ISSUE THREAD

**Issue by arilotter** [Menci/vite-plugin-top-level-await#15]
Hi! I've found a bug where `await import('./xxx')` calls aren't behaving correctly.
The module `./xxx` does end up with a `__tla` export, but the module calling `await import` never gets the `__tla.then(...)` transformation.
I've built a minimal example here: https://github.com/arilotter/async-import-bug that repros the bug 100% of the time :)

It uses some proprietary code from my company in the `wasm-package` folder, but everything inside the `consumer-package` folder is free to use, etc. - i just can't license the `wasm-package` code to be used in a test or anything. Should be easy enough to repro without the proprietary code, though!
Let me know if I can help :)

**Comment by Menci** [comment]
Thanks. I'll check it.

**Comment by Menci** [comment]
Fixed in `v1.2.2`
