### ISSUE TITLE
Build issue (`Fallback bindings does not support this interface yet`)

### ISSUE THREAD

**Issue by brianorwhatever** [Menci/vite-plugin-top-level-await#17]
I am running into the same issue as #14 and have updated to the versions they used and am still not having any luck. This blew up in my build pipeline suddenly one day.. Any ideas?
```
#12 17.09 Error: Fallback bindings does not support this interface yet.
#12 17.09     at Compiler.<anonymous> (/app/node_modules/@swc/core/index.js:119:23)
#12 17.09     at Generator.next (<anonymous>)
#12 17.09     at /app/node_modules/@swc/core/index.js:34:71
#12 17.09     at new Promise (<anonymous>)
#12 17.09     at __awaiter (/app/node_modules/@swc/core/index.js:30:12)
#12 17.09     at Compiler.parse (/app/node_modules/@swc/core/index.js:115:16)
#12 17.09     at Object.parse (/app/node_modules/@swc/core/index.js:320:21)
#12 17.09     at /app/node_modules/vite-plugin-top-level-await/dist/bundle-info.js:33:19
#12 17.09     at Array.map (<anonymous>)
#12 17.09     at parseBundleAsts (/app/node_modules/vite-plugin-top-level-await/dist/bundle-info.js:31:78)
```

**Comment by brianorwhatever** [comment]
Downgrading to vite 3.1.8 did not solve the issue btw

**Comment by Menci** [comment]
This is a SWC native binding issue and have nothing to do with Vite.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/11341955/205967905-021819d6-b20d-46ae-b0ca-968d255bba22.png">

On my machine it works with Vite 3.2.5, Node.js 18.11.0 and Yarn 1.22.19.

**Comment by Menci** [comment]
It works on CI. The unit tests are passed: https://github.com/Menci/vite-plugin-top-level-await/actions/runs/3631498853/jobs/6126214204

<img width="932" alt="image" src="https://user-images.githubusercontent.com/11341955/205970598-402648cc-dc04-40f5-81f2-f5cb7132e56b.png">

I still believe it's nothing to do with Vite.

**Comment by brianorwhatever** [comment]
yeah agreed I don't think it's vite either. I tried with ubuntu image but having the same issue. I guess I will just target `esnext` for now.. 😮‍💨

**Comment by Menci** [comment]
Do you have some server that could reproduce this issue for me to debug it remotely? I'm afriad it's related to your environment setup.

**Comment by Menci** [comment]
Closed since no response
