### ISSUE TITLE
Bindings not found

### ISSUE THREAD

**Issue by TheUniParse** [Menci/vite-plugin-top-level-await#25]
in  windows 10 evrything works fine, but in windows 11 I have this error even if main.js are empty in new project
<pre>
$ pnpm build

> test@0.0.0 build C:\Users\UniParse\projects\test
> vite build

vite v4.1.4 building for production...
✓ 3 modules transformed.
rendering chunks (1)...[vite-plugin-top-level-await] Bindings not found.
error during build:
Error: Bindings not found.
    at Compiler.<anonymous> (C:\Users\UniParse\projects\test\node_modules\.pnpm\@swc+core@1.3.36\node_modules\@swc\core\index.js:122:23)
    at Generator.next (<anonymous>)
    at C:\Users\UniParse\projects\test\node_modules\.pnpm\@swc+core@1.3.36\node_modules\@swc\core\index.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\UniParse\projects\test\node_modules\.pnpm\@swc+core@1.3.36\node_modules\@swc\core\index.js:30:12)
    at Compiler.parse (C:\Users\UniParse\projects\test\node_modules\.pnpm\@swc+core@1.3.36\node_modules\@swc\core\index.js:115:16)
    at Object.parse (C:\Users\UniParse\projects\test\node_modules\.pnpm\@swc+core@1.3.36\node_modules\@swc\core\index.js:320:21)
    at C:\Users\UniParse\projects\test\node_modules\.pnpm\vite-plugin-top-level-await@1.3.0_vite@4.1.4\node_modules\vite-plugin-top-level-await\dist\bundle-info.js:33:19
    at Array.map (<anonymous>)
    at parseBundleAsts (C:\Users\UniParse\projects\test\node_modules\.pnpm\vite-plugin-top-level-await@1.3.0_vite@4.1.4\node_modules\vite-plugin-top-level-await\dist\bundle-info.js:31:78)
 ELIFECYCLE  Command failed with exit code 1.
</pre>

**Comment by TheUniParse** [comment]
my vite config:
<pre>
import { defineConfig } from 'vite'
import topLevelAwait from 'vite-plugin-top-level-await'

export default defineConfig({
  base: './',
  plugins: [
    topLevelAwait({
      promiseExportName: "__tla",
      promiseImportName: i => `__tla_${i}`
    })
  ]
})
</pre>

**Comment by Menci** [comment]
Did you tried removing node_modules and reinstalling dependencies?

**Comment by TheUniParse** [comment]
thanks for your answer @Menci , 
but I still have this error after removing node_modules & reinstalling,
I even tried to downgrade to differ minor versions 1.3.0  1.2.4  1.1.1 1.0.1

for now I back to use the asyc IIFE wrapper (async ()=>{})();

**Comment by TheUniParse** [comment]
I don't know why, but its works just fine now!!
I just reinstalled it <code>pnpm add -D vite-plugin-top-level-await</code>

**Comment by Menci** [comment]
I did't do anything about it. Strange...

**Comment by TheUniParse** [comment]
my bad, i was thinking that i did pnpm build, but I didn't, now I still have the same issue.

**Comment by Menci** [comment]
Hi. Let's continue investigate on this. How can I reproduce it?

Could you try reproduce it with a simple project in a (reproducable, e.g. Docker) environment?

**Comment by Menci** [comment]
Hi. Let's continue investigate on this. How can I reproduce it?

Could you try reproduce it with a simple project in a (reproducable, e.g. Docker) environment?

**Comment by SAY-yes** [comment]
I have the same error.
OS       win10
node  v18.16.0
npm    9.5.1

"react": "^18.2.0"
 "vite": "^3.0.7"
"vite-plugin-top-level-await": "^1.2.1"

my config is same as [TheUniParse](https://github.com/TheUniParse)
npm start,  it works well.
but build it, it has error.

Error Information：
> react-template@0.0.0 build
> tsc && vite build

vite v3.2.6 building for production...
✓ 3012 modules transformed.
rendering chunks (1)...[vite-plugin-top-level-await] Bindings not found.

PWA v0.13.3
mode      generateSW
precache  2 entries (1.46 KiB)
files generated
  dist\sw.js
  dist\workbox-c0ce6236.js
error during build:
Error: Bindings not found.
    at Compiler.<anonymous> (E:\xx\xx\node_modules\@swc\core\index.js:122:23)
    at Generator.next (<anonymous>)
    at E:\xx\xx\node_modules\@swc\core\index.:71
    at new Promise (<anonymous>)
    at __awaiter (E:\xx\xx\node_modules\@swc\index.js:30:12)
    at Compiler.parse (E:\xx\xx\node_modules\core\index.js:115:16)
    at Object.parse (E:\xx\xx\node_modules\@sre\index.js:320:21)
    at E:\xx\xx\node_modules\vite-plugin-top--await\dist\bundle-info.js:33:19
    at Array.map (<anonymous>)
    at parseBundleAsts (E:\xx\xx\node_modules\vite-plugin-top-level-await\dist\bundle-info.js:31:78)
    at Object.generateBundle (E:\xx\xx\node_modules\vite-plugin-top-level-await\dist\index.js:86:72)
    at file:///E:/xx/xx/node_modules/rollup/dist/es/shared/rollup.js:22748:40

**Comment by TheUniParse** [comment]
> Hi. Let's continue investigate on this. How can I reproduce it?
> 
> Could you try reproduce it with a simple project in a (reproducable, e.g. Docker) environment?

<h2>Hi @Menci</h2>
<dl>
  <dd>unfortunately I lost access to my old environment (official windows 11)</dd>
  <dd>now I'm using <a href=https://windowsxlite.com/win11/>unofficial windows11</a></dd>
  <dd>its custom build without <b>windows defender</b></dd>
  <dd>now everything works, <code>pnpm build</code> && <code>pnpm preview</code>, <b>no errors</b></dd>
</dl>

**Comment by HeeBooo** [comment]
The same problem happened to me. May I ask how you solved it? @TheUniParse

**Comment by TheUniParse** [comment]
<h2>Hi @HeeBooo</h2>
<dl>
<dd>I don't think I solved anything in particular</dd>
<dd>and I think the problem has direct relationship with <b>windows defender</b></dd>
<dd>I just installed <a href=https://windowsxlite.com/win11/>unofficial windows11</a>, which does not have <b>windows defender</b></dd>
</dl>

**Comment by KekekeLi** [comment]
i have the same problem, and it still troubles me

**Comment by zyq0407** [comment]
I had the same problem and solved it. I found that the '@swc/core-linux-x64-gnu' module was not found, so, I added to the package.json  and reinstalling dependencies.

Dependencies of swc/core in different systems，my vite-plugin-top-level-await version is 1.3.1
    "@swc/core-win32-x64-msvc": "1.3.68",
    "@swc/core-darwin-x64": "1.3.68",
    "@swc/core-linux-x64-gnu": "1.3.68",
    "@swc/core-linux-x64-musl": "1.3.68",
    "@swc/core-win32-ia32-msvc": "1.3.68",
    "@swc/core-linux-arm64-gnu": "1.3.68",
    "@swc/core-linux-arm-gnueabihf": "1.3.68",
    "@swc/core-darwin-arm64": "1.3.68",
    "@swc/core-linux-arm64-musl": "1.3.68",
    "@swc/core-win32-arm64-msvc": "1.3.68"

**Comment by farmaazon** [comment]
> Same issue on my side. I am able to run fine on my windows machine but when building through github actions it explodes

I have exactly the same problem. Are there any plans to fix this?

**Comment by Jiachenglong2518** [comment]
@DMOAbove  me too, May I ask if you have resolved it

**Comment by Jiachenglong2518** [comment]
> I had the same problem and solved it. I found that the '@swc/core-linux-x64-gnu' module was not found, so, I added to the package.json and reinstalling dependencies.
> 
> Dependencies of swc/core in different systems，my vite-plugin-top-level-await version is 1.3.1 "@swc/core-win32-x64-msvc": "1.3.68", "@swc/core-darwin-x64": "1.3.68", "@swc/core-linux-x64-gnu": "1.3.68", "@swc/core-linux-x64-musl": "1.3.68", "@swc/core-win32-ia32-msvc": "1.3.68", "@swc/core-linux-arm64-gnu": "1.3.68", "@swc/core-linux-arm-gnueabihf": "1.3.68", "@swc/core-darwin-arm64": "1.3.68", "@swc/core-linux-arm64-musl": "1.3.68", "@swc/core-win32-arm64-msvc": "1.3.68"



> I had the same problem and solved it. I found that the '@swc/core-linux-x64-gnu' module was not found, so, I added to the package.json and reinstalling dependencies.
> 
> Dependencies of swc/core in different systems，my vite-plugin-top-level-await version is 1.3.1 "@swc/core-win32-x64-msvc": "1.3.68", "@swc/core-darwin-x64": "1.3.68", "@swc/core-linux-x64-gnu": "1.3.68", "@swc/core-linux-x64-musl": "1.3.68", "@swc/core-win32-ia32-msvc": "1.3.68", "@swc/core-linux-arm64-gnu": "1.3.68", "@swc/core-linux-arm-gnueabihf": "1.3.68", "@swc/core-darwin-arm64": "1.3.68", "@swc/core-linux-arm64-musl": "1.3.68", "@swc/core-win32-arm64-msvc": "1.3.68"



> I had the same problem and solved it. I found that the '@swc/core-linux-x64-gnu' module was not found, so, I added to the package.json and reinstalling dependencies.
> 
> Dependencies of swc/core in different systems，my vite-plugin-top-level-await version is 1.3.1 "@swc/core-win32-x64-msvc": "1.3.68", "@swc/core-darwin-x64": "1.3.68", "@swc/core-linux-x64-gnu": "1.3.68", "@swc/core-linux-x64-musl": "1.3.68", "@swc/core-win32-ia32-msvc": "1.3.68", "@swc/core-linux-arm64-gnu": "1.3.68", "@swc/core-linux-arm-gnueabihf": "1.3.68", "@swc/core-darwin-arm64": "1.3.68", "@swc/core-linux-arm64-musl": "1.3.68", "@swc/core-win32-arm64-msvc": "1.3.68"

@zyq0407  Your posting method solves my problem

**Comment by asyncTime** [comment]
hello, how you solved it?
