### ISSUE TITLE
  [vite-plugin-top-level-await] Failed to convert rust String into napi string

### ISSUE THREAD

**Issue by kkarry** [Menci/vite-plugin-top-level-await#28]
vueV3.2.47+viteV4.2.1+nodeV18.15.0+npmV9.5.0 +vite-plugin-top-level-awaitV1.3.0
npm run build   Error:

[vite-plugin-top-level-await] Failed to convert rust String into napi string

**Comment by Menci** [comment]
Could you please provide a simple project to reproduce this? Thank.

**Comment by Menci** [comment]
Closing since no response.
