### ISSUE TITLE
Module format "umd" does not support top-level await. Use the "es" or "system" output formats rather.

### ISSUE THREAD

**Issue by OneSeven** [Menci/vite-plugin-top-level-await#29]
Doesn't support UMD output?

**Comment by Menci** [comment]
Vite doesn't support UMD.

**Comment by ben-xD** [comment]
I get a similar error:
```
[web-extension:manifest] Module format "iife" does not support top-level await. Use the "es" or "system" output formats rather.
```

Does it also not support `iife`? Is there more information to help me debug why Vite doesn't support UMD or IIFE? I guess it only supports em and cjs.

**Comment by ceynri** [comment]
I found can use`rollup-plugin-tla` to resolve umd format top-level-await support.

**Comment by dimisus** [comment]
> I found can use`rollup-plugin-tla` to resolve umd format top-level-await support.

found this by accident, solved my problem. u sexy
