### ISSUE TITLE
Crashes when dynamically importing built-in modules (path, url, fs etc)

### ISSUE THREAD

**Issue by boyeborg** [Menci/vite-plugin-top-level-await#4]
The plugin crashes when you try to dynamically import a built-in module (like `path`, `url`, `fs` etc). It seems like the plugin fails when trying to [look up `transformNeeded` from the bundleInfo](https://github.com/Menci/vite-plugin-top-level-await/blob/0202ccd49880f446d7f3606eb06f7cb0559f872a/src/transform.ts#L176) on the built-in module. I guess it isn't included there since it's a built-in?

**Comment by Menci** [comment]
You mentioned SSR in your issue on my another repo. Does this issue also happens on SSR?

**Comment by boyeborg** [comment]
Adding an optional chaining (?) to [the line mentioned above](https://github.com/Menci/vite-plugin-top-level-await/blob/0202ccd49880f446d7f3606eb06f7cb0559f872a/src/transform.ts#L176) allows everything to build as expected, but I'm not sure it actually fixes the problem:

```js
if (importedModuleName && !bundleInfo[importedModuleName]?.transformNeeded) return call;
```
