### ISSUE TITLE
The plugin don't parse a file that only contains ´ExportNamedDeclaration´ with source

### ISSUE THREAD

**Issue by pedrotainha** [Menci/vite-plugin-top-level-await#45]
Consider the example of a file that arrives in these conditions at the plugin execution:
`
export {a, b, c} from 'somefile.js'
`
where the `somefile.js` will also be parsed by the plugin

This is an ExportNamedDeclaration and the plugin is only expecting ImportDeclaration to parse.  Due to this, it will fail at run time because it will not resolve the somefile.js returning immediately the exports without waiting for their assignment in the promise of the `somefile.js`

**Comment by Menci** [comment]
It makes sense! I didn't find any real world Vite output example of `export {} from "...";` statements so I didn't implement that. I had many assumptions of Vite's output code at the time of starting this project. Now let's fix it! Thanks.
