### ISSUE TITLE
[vite-plugin-top-level-await] missing field `ctxt`

### ISSUE THREAD

**Issue by dugufu** [Menci/vite-plugin-top-level-await#52]
![image](https://github.com/user-attachments/assets/750253c9-bb9d-4911-ac7f-0ae5b3334110)

**Comment by Baiyouzhai** [comment]
My project construction also encountered this issue

**Comment by dugufu** [comment]
> My project construction also encountered this issue

大哥你是 本地build 还是上面build的时候出问题 
我刚刚解决了

**Comment by dugufu** [comment]
For my package.json

{
   "vite": "^4.5.1",
    "vite-plugin-ejs": "^1.7.0",
    "vite-plugin-top-level-await": "^1.4.1" //update this to latest version
}


Then rm -r node_modules/ 
Then run build again

**Comment by dugufu** [comment]
For my case I cant build the dist on github actions
So I update my yml file
`
name: Publish Panel Prod
on:
  workflow_dispatch:
  push:
    tags:
      - panel-prod-v*
    paths:
      - packages/panel/**
jobs:
  deploy:
    name: Preview Panel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 **use this version**

      - name: Setup Nodejs and yarn with cache
        uses: actions/setup-node@v4 **update this**
        with:
          node-version: "18"

      - uses: pnpm/action-setup@v2 **use this version**
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9 **use this version**
          run_install: false

      - name: Install dependencies
        working-directory: "packages"
        run: cd backend && pnpm i && cd ../panel && pnpm i

      - name: Build
        working-directory: "packages/panel"
        run: pnpm run build:prod

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_PROD }}
          accountId: ${{ secrets.CF_ACCOUNT_ID_PROD }}
          workingDirectory: "packages/panel/dist"
          command: pages publish spa --project-name=abc--commit-hash $GITHUB_SHA --branch main

`

**Comment by dugufu** [comment]
`production.yml
name: Publish Panel Prod
on:
  workflow_dispatch:
  push:
    tags:
      - panel-prod-v*
    paths:
      - packages/panel/**
jobs:
  deploy:
    name: Preview Panel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 **use this version**

      - name: Setup Nodejs and yarn with cache
        uses: actions/setup-node@v4 **update this**
        with:
          node-version: "18"

      - uses: pnpm/action-setup@v2 **use this version**
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9 **use this version**
          run_install: false

      - name: Install dependencies
        working-directory: "packages"
        run: cd backend && pnpm i && cd ../panel && pnpm i

      - name: Build
        working-directory: "packages/panel"
        run: pnpm run build:prod

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_PROD }}
          accountId: ${{ secrets.CF_ACCOUNT_ID_PROD }}
          workingDirectory: "packages/panel/dist"
          command: pages publish spa --project-name=abc--commit-hash $GITHUB_SHA --branch main`

**Comment by dugufu** [comment]
At the end I use correct version and change the yml to correct version then fixed

**Comment by F-loat** [comment]
worked for me

``` sh
pnpm i -D @swc/core@~1.6.0
```

**Comment by z100h100** [comment]
我也出现这个情况了 本地build  前段时间还是好的
![微信图片_20240718181059](https://github.com/user-attachments/assets/3b24b739-4488-4706-b990-b859643430e0)

**Comment by F-loat** [comment]
@z100h100 `@swc/core` 今天发了 1.7.0 版本，应该是有些不兼容

**Comment by z100h100** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by z100h100** [comment]
@F-loat 好的 我暂时先去掉这个了

**Comment by noreng** [comment]
I faced to the same issue. I use pnpm, adding this to the package.json to temporary fix:
```
"pnpm": {
    "overrides": {
        "@swc/core": "1.6.0"
    }
}
```
You can do similar with other package managers until this plugin has a proper fix.

**Comment by Robin-Ln** [comment]
i have the same issue

**Comment by Chriztiaan** [comment]
I recommend locking the swc/core version in this package or investigating whether this is a bug in `swc`.

**Comment by jyjgit** [comment]
现在有解决方案吗，我目前也遇到这个问题😭

**Comment by luyaozi** [comment]
留个名 我也遇到了

**Comment by zmannnnn** [comment]
package.json 固定@swc/core版本为1.6.13
`
{"resolutions": {
    "**/vite-plugin-top-level-await/@swc/core": "1.6.13" 
  }
}
`

**Comment by zmannnnn** [comment]
> 留个名 我也遇到了

![企业微信截图_20240719142544](https://github.com/user-attachments/assets/ad5d1a11-748d-4623-b3fd-0f734cd9c39c)

**Comment by zmannnnn** [comment]
> 现在有解决方案吗，我目前也遇到这个问题😭

![Uploading 企业微信截图_20240719142544.png…]()

**Comment by ningmengxiaorui** [comment]
留个名，我也遇到了

**Comment by sanhui33** [comment]
headache :(

**Comment by zhaona123zn** [comment]
![image](https://github.com/user-attachments/assets/f037ccc6-3bb6-47df-bfc8-4625a8066438)

**Comment by webaddkevin** [comment]
me to  @swc/core 不兼容 回退版本

**Comment by Menci** [comment]
The definition of `ctxt` field is missing from SWC's typing definitions... I tested and added the field to everywhere the latest SWC requires. I have no time to fix it for SWC...

Pushed `v1.4.2`, which should have this issue fixed.

**Comment by MicahZJ** [comment]
> worked for me
> 
> ```shell
> pnpm i -D @swc/core@~1.6.0
> ```

确实是版本问题

**Comment by z100h100** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
