### ISSUE TITLE
Support for vite 3.0.0 ?

### ISSUE THREAD

**Issue by valerii15298** [Menci/vite-plugin-top-level-await#6]
Support for vite 3.0.0?

**Comment by Menci** [comment]
What's the problem?

I just adopt my plugin [`vite-plugin-wasm`](https://github.com/Menci/vite-plugin-wasm/tree/2.x) to Vite 3 and found this plugin worked out of the box.

**Comment by valerii15298** [comment]
What I mean is that when I install it with pnpm this is what I got:
```
vite-plugin-top-level-await
  └── ✕ unmet peer vite@^2.8: found 3.0.0
```

**Comment by valerii15298** [comment]
It seems you already fixed it in last release. So thank you!!! Closing it then. I do not see this warning anymore

**Comment by Menci** [comment]
I just edited the `peerDependencies` version.
