### ISSUE TITLE
error occured like this

### ISSUE THREAD

**Issue by Chasen-Zhang** [Menci/vite-plugin-top-level-await#9]
<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa3ac10 node::Abort() [node]
 2: 0x970199 node::FatalError(char const*, char const*) [node]
 3: 0xbba5ce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xbba947 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd76b65  [node]
 6: 0xda74fe v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xdb3536 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 8: 0xd9f6cf v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
 9: 0xd9f948 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
10: 0xd92229 v8::internal::ItemParallelJob::Run() [node]
11: 0xdb5490 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
12: 0xdb5d2c v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
13: 0xdb5ef5 v8::internal::MarkCompactCollector::Evacuate() [node]
14: 0xdc7ef1 v8::internal::MarkCompactCollector::CollectGarbage() [node]
15: 0xd841b8 v8::internal::Heap::MarkCompact() [node]
16: 0xd85ca8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
17: 0xd87be5 v8::internal::Heap::HandleGCRequest() [node]
18: 0xd2e0f7 v8::internal::StackGuard::HandleInterrupts() [node]
19: 0x109f7e3 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
20: 0x1448f99  [node]

**Comment by Menci** [comment]
Try [increasing your Node.js heap size limit](https://stackoverflow.com/a/53877027) with:

```bash
NODE_OPTIONS=--max-old-space-size=8192 yarn build
```

In which 8192 means 8192 MiB, aka 8 GiB.
